apiVersion: v1
kind: Namespace
metadata:
  name: devin-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: devin-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: devin-sandboxes
---
apiVersion: v1
kind: Namespace
metadata:
  name: devin-firecracker
